spring:
  datasource:
    url: jdbc:postgresql://localhost/product_db
    username: product_db
    password: product_db
server:
  error:
    include-stacktrace: on_param
    include-message: always
logging:
  level:
    org:
      springframework:
        security: WARN
